name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: week2-m1-test
      id: week2-m1-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: week2-m1-test
        setup-command: ''
        command: python3 main.py
        input: ''
        expected-output: ".*총.*결제.*금액은.*36000.*원.*입니다.*"
        comparison-method: regex
        timeout: 1
        max-score: 29
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        WEEK2-M1-TEST_RESULTS: "${{steps.week2-m1-test.outputs.result}}"
      with:
        runners: week2-m1-test
